version: '3'
services:
  frontend:
    build: frontend
    tty: true
    ports:
      - 8080:3000
    volumes:
      - ./frontend/src:/app
  backend:
    build: backend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app
    tmpfs:
      - /data:mode=777,uid=1000,gid=1000
    environment:
      SCHEDULES_PATH: /data
